language: android
android:
  components:
  - android-21
  - build-tools-21.1.2
env:
  global:
  - secure: KuCVpSmLqbTDgKz9ZHTQOjTjcBPNXGVLw4+LNShhd88tWwPYnhJ97F7CV8mILOSc6iAUUiix3ZpPLqUNciWaqhVtC4WyQEQxPz+ypb4CuuwtcgE6mo+KD1Q0L/vLLUJjhVB2VsolXK07YRTwbmI912Cg7HuOB1U/vn5/4mc824U=
  - secure: fkd8jVD1ucRB6GeN7FLte0p0Z/pnErFw2Z1pokxAp/0nJCIt7+GFmY0sXataWer05VXyzt+aw5ZUt8LvqA8XP4WqmPXrW8g+uoZniO7rkV4FvtlXPinG6Zg6t7Mnn65rjgEpC5dvdxEdpmf21IfG2Y7nyi0ckBh8pwZmYf8PBPA=
before_install:
- openssl aes-256-cbc -K $encrypted_ac4e281d93a4_key -iv $encrypted_ac4e281d93a4_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- mv madfau.keystore app/
script: "./gradlew assemble"
after_success:
- mv app/build/outputs/apk/app-release.apk fablab-android-$TRAVIS_BRANCH-`git rev-parse
  HEAD`.apk
- curl -u $LOGIN -F "apk=@fablab-android-$TRAVIS_BRANCH-`git rev-parse HEAD`.apk"
  -F "project=fablab-android" $URL
